### ISSUE TITLE
Invoice Items and Invoice Images pagination do not work

### ISSUE THREAD

**Issue by mfernandagf** [Fielo-Plugins/fielocms-fieloprp#1]
Even having items to paginate, when clicking "Next" link, no new items are shown

**Comment by tibeal** [comment]
There will be a call with Hugo to see how this can be done.

**Comment by tibeal** [comment]
It was developed a Javascript class to set filters on RecordSet paginators.

This issue is now fixed.

**Note:** There are some known issues:
 - The **next** button is not getting disabled when the number of the records  and records per page are multiples. For example, if there are 12 records and the component has configured 6 records per page, the next button will be enabled in the second page, but will show a message that there are no records to display.
 - Lookup fields that should display the record name are getting changed to its Id when paginating.
